# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:fo808
  push:foring
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: https://wikitech.wikimedia.org/wiki/User:Forcing
  build: fo808

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps: https://wikitech.wikimedia.org/wiki/Deployments#!/deploycal/current
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm 
    - run: npm run build --if-present
    - run: npm 
